/* eslint-disable */
export const ActionType = {
  FETCH_INITIAL_DATA: 'FETCH_INITIAL_DATA',
  SET_MOVIE_LIST: 'SET_MOVIE_LIST',
  SET_RUBRIC_LIST: 'SET_RUBRIC_LIST',
  SET_NEW_LIST: 'SET_NEW_LIST',
  ADD_FILM: 'ADD_FILM',
}