/* eslint-disable */
export const ActionType = {
  FETCH_INITIAL_DATA: 'FETCH_INITIAL_DATA',
  SET_MOVIE_LIST: 'SET_MOVIE_LIST',
  SET_RUBRIC_LIST: 'SET_RUBRIC_LIST',
  SET_NEW_LIST: 'SET_NEW_LIST',
  SEARCH_FILM: 'SEARCH_FILM',
  FIND_MOVIE: 'FIND_MOVIE',
  INPUT_CHANGED: 'INPUT_CHANGED',
}